<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="frmDataSourceTotal.aspx.cs" Inherits="DataBindingPrueba.frmDataSourceTotal" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:SqlDataSource ID="SourceProducts" runat="server"
                ProviderName="System.Data.OleDb"
                ConnectionString="<%$ ConnectionStrings:Northwind %>"
                SelectCommand="SELECT Id, [Nombre del producto], [Costo estándar],
                Suspendido, [Cantidad miníma de reposición], [Precio listado] FROM Productos"
                UpdateCommand="UPDATE Productos SET [Nombre del producto=@nombre], 
                [Costo estándar]=@costo,[Cantidad mínima de reposición]=@stock, Suspendido=@susp,
                [Precio listado]=@precio where Id=@ProductoId"
                DeleteCommand="DELETE Productos WHERE Id=@ProductoId"
                InsertCommand="INSERT INTO Productos ([Nombre del producto],[Costo estándar], Suspendido,
                [Cantidad miníma de reposición],[Precio listado])
                VALUES (@nombre, @costo,@susp,@stock,@precio)">
                <UpdateParameters></UpdateParameters>
                <DeleteParameters></DeleteParameters>
                <InsertParameters></InsertParameters>
                <SelectParameters></SelectParameters>
            </asp:SqlDataSource>
        
            <asp:DetailsView ID="DetailsView1" runat="server" Height="50px" Width="125px"
                DataKeyNames="Id" AllowPaging="true" DataSourceID="SourceProducts"
                AutoGenerateInsertButton="true" AutoGenerateEditButton="true"
                AutoGenerateDeleteButton="true">
                <PagerSettings PageButtonCount="25" />
            </asp:DetailsView>
        
        
        </div>
    </form>
</body>
</html>
